version: '3.7'

services:
    service:
        build:
            context: ./service
            dockerfile: Dockerfile.dev
        image: mjheverett/bookmode-api:dev
        volumes:
            - /app/node_modules
            - ./service/config:/app/config
        ports:
            - "3000:3000"
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        image: mjheverett/bookmode-client:dev
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - "8080:8080"
